### ISSUE TITLE
Recommendation: milight folder to separate repo as PlatformIO Library

### ISSUE THREAD

**Issue by shbatm** [hencou/esphome_components#4]
Wanted to recommend that you split the `milight` folder into a separate repository and structure it like a PlatformIO library.

Reason: this allows you to include the library from GitHub in your ESPHome config instead of needing to copy it to the directory manually and update it every time changes are made to the repo. 

I've already created a test repo and tested this method using the following snippet:

```yaml
esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini
  libraries:
    - milight=https://github.com/shbatm/esphome-milight#main
```

The only issue I found was that I had to directly incorporate the color conversion functions instead of referencing the `esphome.h` functions -- the way PlatformIO compiles the library, using this as is would mean adding the full `esphome` library as a dependency for only these two functions.

I made the repo for the library here: https://github.com/shbatm/esphome-milight; I'd be happy to transfer ownership to you if you want to use this method.

Thanks again for all the work!
